name: GitHub CI

on:
 push:
  paths:
   - 'build.py'
   - 'Pipfile'
   - '.github/workflows/nuitka.yml'
   - 'pyro/**'
   - 'tools/**'
  branches:
   - master
 workflow_dispatch:

jobs:
 build:
  
  runs-on: windows-latest
  
  steps:
   - uses: actions/checkout@v1
   - name: Set up Visual Studio environment
     if: success()
     uses: seanmiddleditch/gha-setup-vsdevenv@master
   - name: Set up Python 3.10.4 (x64)
     if: success()
     uses: actions/setup-python@v2
     with:
      python-version: 3.10.4
      architecture: x64
   - name: Create virtual environment
     if: success()
     run: python -m venv env
   - name: Install requirements
     if: success()
     run: pip install -r requirements.txt
   - name: Run build script
     if: success()
     run: python D:\a\pyro\pyro\build.py --no-zip
   - name: Upload artifact
     if: success()
     uses: actions/upload-artifact@v1
     with:
      name: pyro-master-${{ github.event.repository.pushed_at }}
      path: D:\a\pyro\pyro\pyro.dist
